import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Consult",
    link: "/consult",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: spfOne,
    productName: "Cap for Boys",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "202",
    img: newArrFour,
    productName: "Tea Table",
    price: "180.00",
    color: "Gray",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "203",
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "204",
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: 1001,
    img: "https://cdn01.pharmeasy.in/dam/products_otc/I01439/episoft-ac-sunscreen-spf30-cream-75gm-6.1-1718975150.jpg?dim=360x360&q=75",
    productName: "Product 1",
    price: "35.00",
    color: "Category 1",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1002,
    img: "https://images.apollo247.in/pub/media/catalog/product/A/P/APM0010_1-JULY23_1.jpg?tr=w-400,q-100,f-webp,c-at_max",
    productName: "Product 2",
    price: "180.00",
    color: "Category 2",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1003,
    img: "https://swadesii.com/cdn/shop/products/download-2022-11-25T170744.091.jpg?v=1679642928",
    productName: "Product 3",
    price: "25.00",
    color: "Category 3",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1004,
    img: "https://images.pexels.com/photos/7852734/pexels-photo-7852734.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 4",
    price: "220.00",
    color: "Category 4",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1005,
    img: "https://images.pexels.com/photos/7852733/pexels-photo-7852733.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 5",
    price: "35.00",
    color: "Category 5",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1006,
    img: "https://images.pexels.com/photos/8533216/pexels-photo-8533216.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 6",
    price: "180.00",
    color: "Category 1",
    badge: false,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1007,
    img: "https://images.pexels.com/photos/8533214/pexels-photo-8533214.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 7",
    price: "25.00",
    color: "Category 2",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1008,
    img: "https://images.pexels.com/photos/5632330/pexels-photo-5632330.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 8",
    price: "220.00",
    color: "Category 3",
    badge: false,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1009,
    img: "https://images.pexels.com/photos/5632356/pexels-photo-5632356.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 9",
    price: "44.00",
    color: "Category 4",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1010,
    img: "https://images.pexels.com/photos/28116998/pexels-photo-28116998/free-photo-of-a-bottle-of-a-facial-cream-sitting-on-a-table.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 10",
    price: "250.00",
    color: "Category 5",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1011,
    img: "https://images.pexels.com/photos/27849608/pexels-photo-27849608/free-photo-of-cosmetic-product-hair-removal-cream.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 11",
    price: "80.00",
    color: "Category 1",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1012,
    img: "http://localhost:3000/static/media/newArrFour.b8a5fda6839f2f0b1eaa.webp",
    productName: "Product 12",
    price: "60.00",
    color: "Category 2",
    badge: false,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1013,
    img: "https://cdn01.pharmeasy.in/dam/products_otc/I01439/episoft-ac-sunscreen-spf30-cream-75gm-6.1-1718975150.jpg?dim=360x360&q=75",
    productName: "Product 1",
    price: "35.00",
    color: "Category 1",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1014,
    img: "https://images.apollo247.in/pub/media/catalog/product/A/P/APM0010_1-JULY23_1.jpg?tr=w-400,q-100,f-webp,c-at_max",
    productName: "Product 2",
    price: "180.00",
    color: "Category 2",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1015,
    img: "https://swadesii.com/cdn/shop/products/download-2022-11-25T170744.091.jpg?v=1679642928",
    productName: "Product 3",
    price: "25.00",
    color: "Category 3",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1016,
    img: "https://images.pexels.com/photos/7852734/pexels-photo-7852734.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 4",
    price: "220.00",
    color: "Category 4",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1017,
    img: "https://images.pexels.com/photos/7852733/pexels-photo-7852733.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 5",
    price: "35.00",
    color: "Category 5",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1018,
    img: "https://images.pexels.com/photos/8533216/pexels-photo-8533216.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 6",
    price: "180.00",
    color: "Category 1",
    badge: false,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1019,
    img: "https://images.pexels.com/photos/8533214/pexels-photo-8533214.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 7",
    price: "25.00",
    color: "Category 2",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1020,
    img: "https://images.pexels.com/photos/5632330/pexels-photo-5632330.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 8",
    price: "220.00",
    color: "Category 3",
    badge: false,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1021,
    img: "https://images.pexels.com/photos/5632356/pexels-photo-5632356.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 9",
    price: "44.00",
    color: "Category 4",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1022,
    img: "https://images.pexels.com/photos/28116998/pexels-photo-28116998/free-photo-of-a-bottle-of-a-facial-cream-sitting-on-a-table.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 10",
    price: "250.00",
    color: "Category 5",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1023,
    img: "https://images.pexels.com/photos/27849608/pexels-photo-27849608/free-photo-of-cosmetic-product-hair-removal-cream.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 11",
    price: "80.00",
    color: "Category 1",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1024,
    img: "http://localhost:3000/static/media/newArrFour.b8a5fda6839f2f0b1eaa.webp",
    productName: "Product 12",
    price: "60.00",
    color: "Category 2",
    badge: false,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1025,
    img: "https://cdn01.pharmeasy.in/dam/products_otc/I01439/episoft-ac-sunscreen-spf30-cream-75gm-6.1-1718975150.jpg?dim=360x360&q=75",
    productName: "Product 1",
    price: "35.00",
    color: "Category 1",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1026,
    img: "https://images.apollo247.in/pub/media/catalog/product/A/P/APM0010_1-JULY23_1.jpg?tr=w-400,q-100,f-webp,c-at_max",
    productName: "Product 2",
    price: "180.00",
    color: "Category 2",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1027,
    img: "https://swadesii.com/cdn/shop/products/download-2022-11-25T170744.091.jpg?v=1679642928",
    productName: "Product 3",
    price: "25.00",
    color: "Category 3",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1028,
    img: "https://images.pexels.com/photos/7852734/pexels-photo-7852734.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 4",
    price: "220.00",
    color: "Category 4",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1029,
    img: "https://images.pexels.com/photos/7852733/pexels-photo-7852733.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 5",
    price: "35.00",
    color: "Category 5",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1030,
    img: "https://images.pexels.com/photos/8533216/pexels-photo-8533216.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 6",
    price: "180.00",
    color: "Category 1",
    badge: false,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1031,
    img: "https://images.pexels.com/photos/8533214/pexels-photo-8533214.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 7",
    price: "25.00",
    color: "Category 2",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1032,
    img: "https://images.pexels.com/photos/5632330/pexels-photo-5632330.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 8",
    price: "220.00",
    color: "Category 3",
    badge: false,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1033,
    img: "https://images.pexels.com/photos/5632356/pexels-photo-5632356.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 9",
    price: "44.00",
    color: "Category 4",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1034,
    img: "https://images.pexels.com/photos/28116998/pexels-photo-28116998/free-photo-of-a-bottle-of-a-facial-cream-sitting-on-a-table.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 10",
    price: "250.00",
    color: "Category 5",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1035,
    img: "https://images.pexels.com/photos/27849608/pexels-photo-27849608/free-photo-of-cosmetic-product-hair-removal-cream.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 11",
    price: "80.00",
    color: "Category 1",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1036,
    img: "http://localhost:3000/static/media/newArrFour.b8a5fda6839f2f0b1eaa.webp",
    productName: "Product 12",
    price: "60.00",
    color: "Category 2",
    badge: false,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1037,
    img: "https://cdn01.pharmeasy.in/dam/products_otc/I01439/episoft-ac-sunscreen-spf30-cream-75gm-6.1-1718975150.jpg?dim=360x360&q=75",
    productName: "Product 1",
    price: "35.00",
    color: "Category 1",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1038,
    img: "https://images.apollo247.in/pub/media/catalog/product/A/P/APM0010_1-JULY23_1.jpg?tr=w-400,q-100,f-webp,c-at_max",
    productName: "Product 2",
    price: "180.00",
    color: "Category 2",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1039,
    img: "https://swadesii.com/cdn/shop/products/download-2022-11-25T170744.091.jpg?v=1679642928",
    productName: "Product 3",
    price: "25.00",
    color: "Category 3",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1040,
    img: "https://images.pexels.com/photos/7852734/pexels-photo-7852734.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 4",
    price: "220.00",
    color: "Category 4",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1041,
    img: "https://images.pexels.com/photos/7852733/pexels-photo-7852733.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 5",
    price: "35.00",
    color: "Category 5",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1042,
    img: "https://images.pexels.com/photos/8533216/pexels-photo-8533216.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 6",
    price: "180.00",
    color: "Category 1",
    badge: false,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1043,
    img: "https://images.pexels.com/photos/8533214/pexels-photo-8533214.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 7",
    price: "25.00",
    color: "Category 2",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1044,
    img: "https://images.pexels.com/photos/5632330/pexels-photo-5632330.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 8",
    price: "220.00",
    color: "Category 3",
    badge: false,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1045,
    img: "https://images.pexels.com/photos/5632356/pexels-photo-5632356.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 9",
    price: "44.00",
    color: "Category 4",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1046,
    img: "https://images.pexels.com/photos/28116998/pexels-photo-28116998/free-photo-of-a-bottle-of-a-facial-cream-sitting-on-a-table.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    productName: "Product 10",
    price: "250.00",
    color: "Category 5",
    badge: true,
    isShowList: true,
    isAnotherShowList: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
];
// =================== PaginationItems End here =================
